# Generated by Django 3.1.6 on 2021-02-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferdetails',
            name='accountnumber',
            field=models.CharField(default='SELF', max_length=15),
        ),
    ]
